name = "XNXX"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[[kv_namespaces]]
binding = "v2ray"
id = "2965cfd9b6174ad6abfd301201b9ebf2"




[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }


[vars]
#UUID = "0fbf4f81-2598-4b6a-a623-0ead4cb9efa8"
UUID = "0fbf4f81-2598-4b6a-a623-0ead4cb9efa8"
#, "aaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1", "00000000-0000-0000-0000-000000000000"]
MAIN_PAGE_URL = "https://raw.githubusercontent.com/kcepu877/bot/refs/heads/main/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/kcepu877/bot/refs/heads/main/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/kcepu877/bot/refs/heads/main/link.html"

[[routes]]
pattern = "dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.dng-google.agenmurah.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.dng-google.agenmurah.xyz"
custom_domain = true
